=== ellak-monades-aristeias/simbug/java-definitions/src/gr/aua/simbug/definition/definition.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">


  <xs:complexType name="ParameterType">
  	<xs:sequence>
		<xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
		<xs:element name="Type" type="dataType" minOccurs="1" maxOccurs="1"></xs:element>
		<xs:element name="Value" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
	</xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="VariableType">
  	<xs:sequence>
		<xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
		<xs:element name="Type" type="dataType" minOccurs="1" maxOccurs="1"></xs:element>
	</xs:sequence>
  </xs:complexType>
  
   <xs:complexType name="ExternalDataType">
	   <xs:complexContent>
	   	<xs:extension base="ParameterType">
	   		<xs:sequence>
	   			<xs:element name="uriLocation" type="xs:anyURI"  minOccurs="1" maxOccurs="1" />
	   		</xs:sequence>
	   	</xs:extension>
	   </xs:complexContent>
  </xs:complexType>
  
    <xs:complexType name="PlayerStateVariableDataType">
	   <xs:complexContent>
	   	<xs:extension base="VariableType">
	   		<xs:sequence>
	   			<xs:element name="WorldVisible" type="xs:boolean"  minOccurs="0" maxOccurs="1" default="false" />
	   		</xs:sequence>
	   	</xs:extension>
	   </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="RandomNumberGeneratorType">
  	<xs:sequence>
		<xs:element name="Name" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
		<xs:element name="Expression" type="xs:string" minOccurs="1" maxOccurs="1"></xs:element>
	</xs:sequence>
  </xs:complexType>
  
  
 
  <xs:simpleType name="dataType">
  	<xs:restriction base="xs:string">
  		<xs:enumeration value="Integer" />
  		<xs:enumeration value="Float" />
  		<xs:enumeration value="String" />
  	</xs:restriction>
  </xs:simpleType>
  
  
  
  
  <xs:element name="Definition">
    <xs:complexType>
    	<xs:all>

    		<xs:element name="Configuration">
    			<xs:complexType>
    				<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="Parameter" type="ParameterType" minOccurs="0">
						</xs:element>
					</xs:sequence>
					</xs:complexType>
    		</xs:element>

			<xs:element name="PlayerChoiceVariables">
				<xs:complexType>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="PlayerChoiceVariable" type="VariableType" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="PlayerStateVariables">
				<xs:complexType >
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="UserStateVariable" type="UserStateVariableDataType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="WorldStateVariables">
				<xs:complexType>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="WorldStateVariable" type="VariableType"  />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="ExternalParameters" minOccurs="0">
				<xs:complexType>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="ExternalVariable" type="ExternalDataType"   />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="RandomNumberGenerators">
				<xs:complexType>
					<xs:sequence minOccurs="0" maxOccurs="unbounded">
						<xs:element name="RandomNumberGenerator" type="RandomNumberGeneratorType" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="ChoicesToStateAlgorithm" type="xs:string">
			</xs:element>			
			

    	</xs:all>
    </xs:complexType>
</xs:element>
</xs:schema>

=== ellak-monades-aristeias/simbug/simbug-server/source/test/java/gr/aua/simbug/tests/hello_world.def2.xml
<?xml version="1.0" encoding="UTF-8"?>
<Definition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../definition/definition.xsd">
  <Configuration>
  </Configuration>
  <PlayerChoiceVariables>
    <PlayerChoiceVariable>
      <Name>numberChoice</Name>
      <Type>Integer</Type>
    </PlayerChoiceVariable>
  </PlayerChoiceVariables>
  <PlayerStateVariables>
    <PlayerStateVariable>
      <Name>roundDistanceFromAverage</Name>
      <Type>Float</Type>
    </PlayerStateVariable>
    <PlayerStateVariable>
    	<Name>roundRank</Name>
    	<Type>Integer</Type>
		
    </PlayerStateVariable>
    <PlayerStateVariable>
      <Name>overallScore</Name>
      <Type>Integer</Type>
    </PlayerStateVariable>
  </PlayerStateVariables>
  <WorldStateVariables>
    <WorldStateVariable>
      <Name>averageAllPlayers</Name>
      <Type>Float</Type>
    </WorldStateVariable>
  </WorldStateVariables>
  <ExternalParameters>
  </ExternalParameters>
  <RandomNumberGenerators>
  </RandomNumberGenerators>
  <ChoicesToStateAlgorithm>
  	<![CDATA[
  		RESULTS = new Object();
		RESULTS['WorldStateVariables'] = new Object();
		RESULTS['PlayerStateVariables'] = new Object();
		RESULTS['PlayerStateVariables']['roundDistanceFromAverage'] = new Object();
		RESULTS['PlayerStateVariables']['roundRank'] = new Object();
		RESULTS['PlayerStateVariables']['overallScore'] = new Object();
  		
		sum=0;
		for (i = 0; i < INFO['num_players']; i++) {
			player_id = INFO['players'][i];
		    sum = sum + PLAYER_CHOICE_VARIABLES['numberChoice'][player_id];
		}	
		avg_all = sum/INFO['num_players'];
		RESULTS['WorldStateVariables']['averageAllPlayers'] = avg_all;
		
		distance = new Array(INFO['num_players']);
		for (i = 0; i < INFO['num_players']; i++) {
			player_id = INFO['players'][i];
			distance[i] = Math.abs(avg_all - PLAYER_CHOICE_VARIABLES['numberChoice'][player_id]);
			RESULTS['PlayerStateVariables']['roundDistanceFromAverage'][player_id] = distance[i];
		}	 
		
		rank = new Array(INFO['num_players']);
		for (i = 0; i < INFO['num_players']; i++) {rank[i]=i;}
		
		rank.sort(function (a, b) { return distance[a] < distance[b] ? 1 : distance[a] > distance[b] ? -1 : 0; });
		for (i = 0; i < INFO['num_players']; i++) {
			player_id = INFO['players'][i];
			RESULTS['PlayerStateVariables']['roundRank'][player_id] = rank[i];
			if(INFO['cur_turn']>0) {
				RESULTS['PlayerStateVariables']['overallScore'][player_id] = rank[i] + PLAYER_STATE_VARIABLES['overallScore'][player_id][INFO['cur_turn']-1];
			}
			else {RESULTS['PlayerStateVariables']['overallScore'][player_id] = rank[i];}
		}		
				
	]]>
  
  </ChoicesToStateAlgorithm>
</Definition>

=== ellak-monades-aristeias/simbug/java-definitions/src/gr/aua/simbug/examples/hello_world/hello_world.def.xml
<?xml version="1.0" encoding="UTF-8"?>
<Definition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../definition/definition.xsd">
  <Configuration>
  </Configuration>
  <PlayerChoiceVariables>
    <PlayerChoiceVariable>
      <Name>numberChoice</Name>
      <Type>Integer</Type>
    </PlayerChoiceVariable>
  </PlayerChoiceVariables>
  <PlayerStateVariables>
    <PlayerStateVariable>
      <Name>roundDistanceFromAverage</Name>
      <Type>Float</Type>
    </PlayerStateVariable>
    <PlayerStateVariable>
    	<Name>roundRank</Name>
    	<Type>Float</Type>
		
    </PlayerStateVariable>
    <PlayerStateVariable>
      <Name>overallScore</Name>
      <Type>Float</Type>
    </PlayerStateVariable>
  </PlayerStateVariables>
  <WorldStateVariables>
    <WorldStateVariable>
      <Name>averageAllPlayers</Name>
      <Type>Float</Type>
    </WorldStateVariable>
  </WorldStateVariables>
  <ExternalParameters>
  </ExternalParameters>
  <RandomNumberGenerators>
  </RandomNumberGenerators>
  <ChoicesToStateAlgorithm>
  	<![CDATA[
		//1. calculate average of all players (world level)
		sum=0;
		for (i = 0; i < %%PLAYERS_COUNT%%; i++) {
		    sum = sum + %%VAR_CUR.numberChoice%%[i];
		}	
		%%VAR_CUR.averageAllPlayers%% = sum/%%PLAYERS_COUNT%%;
		
		//2. calculate distance of each player 
		
		//3. compute rank of each player
		
				
	]]>
  
  </ChoicesToStateAlgorithm>
</Definition>

=== ellak-monades-aristeias/simbug/simbug-server/source/test/java/gr/aua/simbug/tests/hello_world.def.xml
<?xml version="1.0" encoding="UTF-8"?>
<Definition xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="../../definition/definition.xsd">
	<Configuration>
	</Configuration>
	<PlayerChoiceVariables>
		<PlayerChoiceVariable>
			<Name>numberChoice</Name>
			<Type>Integer</Type>
		</PlayerChoiceVariable>
	</PlayerChoiceVariables>
	<PlayerStateVariables>
		<PlayerStateVariable>
			<Name>roundDistanceFromAverage</Name>
			<Type>Float</Type>
		</PlayerStateVariable>
		<PlayerStateVariable>
			<Name>roundRank</Name>
			<Type>Integer</Type>
		</PlayerStateVariable>
		<PlayerStateVariable>
			<Name>overallScore</Name>
			<Type>Integer</Type>
		</PlayerStateVariable>
	</PlayerStateVariables>
	<WorldStateVariables>
		<WorldStateVariable>
			<Name>averageAllPlayers</Name>
			<Type>Float</Type>
		</WorldStateVariable>
	</WorldStateVariables>
	<ExternalParameters>
	</ExternalParameters>
	<RandomNumberGenerators>
	</RandomNumberGenerators>
	<ChoicesToStateAlgorithm>
  	<![CDATA[
		//1. calculate average of all players (world level)
		sum=0;
		for (i = 0; i < INFO['num_players']; i++) {
			player_id = INFO['players'][i];
		    sum = sum + PLAYER_CHOICE_VARIABLES['numberChoice'][player_id][INFO['cur_turn']];
		}	
		avg_all = sum/INFO['num_players'];
		RESULTS['WorldStateVariables']['averageAllPlayers'] = avg_all;
		
		//2. calculate distance of each player
		distance = new Array(INFO['num_players']);
		for (i = 0; i < INFO['num_players']; i++) {
			player_id = INFO['players'][i];
			distance[i] = Math.abs(avg_all - PLAYER_CHOICE_VARIABLES['numberChoice'][player_id][INFO['cur_turn']]);
			RESULTS['PlayerStateVariables']['roundDistanceFromAverage'][player_id] = distance[i];
		}	 
		
		//3. compute rank of each player
		rank = new Array(INFO['num_players']);
		for (i = 0; i < INFO['num_players']; i++) {rank[i]=i;}
		
		rank.sort(function (a, b) { return distance[a] < distance[b] ? 1 : distance[a] > distance[b] ? -1 : 0; });
		for (i = 0; i < INFO['num_players']; i++) {
			RESULTS['PlayerStateVariables']['roundRank'][player_id] = rank[i];
		}
		
		if(INFO['cur_turn']>0) {
			RESULTS['PlayerStateVariables']['overallScore'][player_id] = rank[i] + PLAYER_STATE_VARIABLES['overallScore'][player_id][INFO['cur_turn']-1];
		}
		else {RESULTS['PlayerStateVariables']['overallScore'][player_id] = rank[i];}
				
	]]>

	</ChoicesToStateAlgorithm>
</Definition>
