=== ellak-monades-aristeias/simbug/java-definitions/src/definition.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:complexType name="ParameterType">
  	<xs:sequence>
		<xs:element name="Name" type="xs:string"></xs:element>
		<xs:element name="Type" type="dataType"></xs:element>
		<xs:element name="Value" type="xs:string"></xs:element>
	</xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="VariableType">
  	<xs:sequence>
		<xs:element name="Name" type="xs:string"></xs:element>
		<xs:element name="Type" type="dataType"></xs:element>
	</xs:sequence>
  </xs:complexType>
  
   <xs:complexType name="ExternalDataType">
	   <xs:complexContent>
	   	<xs:extension base="VariableType">
	   		<xs:sequence>
	   			<xs:element name="uriLocation" type="xs:anyURI" />
	   		</xs:sequence>
	   	</xs:extension>
	   </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="RandomNumberGeneratorType">
  	<xs:sequence>
		<xs:element name="Name" type="xs:string"></xs:element>
		<xs:element name="Expression" type="xs:string"></xs:element>
	</xs:sequence>
  </xs:complexType>
  
  
 
  <xs:simpleType name="dataType">
  	<xs:restriction base="xs:string">
  		<xs:enumeration value="Integer" />
  		<xs:enumeration value="Float" />
  		<xs:enumeration value="String" />
  	</xs:restriction>
  </xs:simpleType>
  
  
  
  
  <xs:element name="Definitions">
    <xs:complexType>
    	<xs:all>

    		<xs:element name="Configuration"><xs:complexType><xs:all>
						<xs:element name="Parameter" type="ParameterType">
						</xs:element>
						</xs:all></xs:complexType>
    		</xs:element>

			<xs:element name="PlayerChoiceVariables">
				<xs:complexType>
					<xs:all>
						<xs:element name="PlayerChoiceVariable" type="dataType" />
					</xs:all>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="UserStateVariables">
				<xs:complexType>
					<xs:all>
						<xs:element name="UserStateVariable" type="dataType" />
					</xs:all>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="WorldStateVariables">
				<xs:complexType>
					<xs:all>
						<xs:element name="WorldStateVariable" type="dataType" />
					</xs:all>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="ExternalVariables">
				<xs:complexType>
					<xs:all>
						<xs:element name="PlayerChoiceVariable" type="ExternalDataType" />
					</xs:all>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="RandomNumberGenerators">
				<xs:complexType>
					<xs:all>
						<xs:element name="RandomNumberGenerator" type="RandomNumberGeneratorType" />
					</xs:all>
				</xs:complexType>
			</xs:element>
			
			<xs:element name="ChoicesToStateAlgorithm" type="xs:string">
				
			</xs:element>			
			

    	</xs:all>
    </xs:complexType>
</xs:element>
</xs:schema>

=== ellak-monades-aristeias/simbug/java-definitions/src/gr/aua/simbug/definition/definition_example.xml
<?xml version="1.0" encoding="UTF-8"?>
<Definitions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../definition.xsd">
  <Configuration>
    <Parameter>
      <Name>Name</Name>
      <Type>Integer</Type>
      <Value>Value</Value>
    </Parameter>
  </Configuration>
  <PlayerChoiceVariables>
    <PlayerChoiceVariable>
      <Name>Name</Name>
      <Type>Integer</Type>
    </PlayerChoiceVariable>
  </PlayerChoiceVariables>
  <UserStateVariables>
    <UserStateVariable>
      <Name>Name</Name>
      <Type>Integer</Type>
    </UserStateVariable>
  </UserStateVariables>
  <WorldStateVariables>
    <WorldStateVariable>
      <Name>Name</Name>
      <Type>Integer</Type>
    </WorldStateVariable>
  </WorldStateVariables>
  <ExternalVariables>
    <PlayerChoiceVariable>
      <Name>Name</Name>
      <Type>Integer</Type>
      <uriLocation>http://tempuri.org</uriLocation>
    </PlayerChoiceVariable>
  </ExternalVariables>
  <RandomNumberGenerators>
    <RandomNumberGenerator>
      <Name>Name</Name>
      <Expression>Expression</Expression>
    </RandomNumberGenerator>
  </RandomNumberGenerators>
  <ChoicesToStateAlgorithm>ChoicesToStateAlgorithm</ChoicesToStateAlgorithm>
</Definitions>
